#%RAML 1.0 DataType

type: object
properties:
  pid:
    type: integer
    displayName: Production ID
  model?: string
  note?: string
  q:
    type: integer
    displayName: Quantity
  purchase:
    type: object
    properties:
      p:
        type: number
        displayName: price
      t:
        type: number
        displayName: Tax
      s:
        type: number
        displayName: Shipping Fee
      d:
        type: number
        displayName: Discount
        maximum: 0
        required: false
  sell:
    type: object
    properties:
      p:
        type: number
        displayName: price
      t:
        type: number
        displayName: Tax
      s:
        type: number
        displayName: Shipping Fee
      d:
        type: number
        displayName: Discount
        maximum: 0
        required: false
example: |
  {
    "pid": 1,
    "model": "SL33",
    "note": "A gift for brother",
    "q": 2,
    "purchase": {
      "p": 10.0, "t": 0.88, "s": 0.00, "d": -1.20
    },
    "sell": {
      "p": 10.0, "t": 0.88, "s": 3.99, "d": -1.20
    }
  }
