#%RAML 1.0 DataType
displayName: Line Body
type: object
properties:
  p:
    type: number
    displayName: price
  t:
    type: number
    displayName: Tax
  s:
    type: number
    displayName: Shipping Fee
  d:
    type: number
    displayName: Discount
    maximum: 0
    required: false
  total:
    type: number
    displayName: Total price
    required: false
example: |
  {
    "p": 10.0,
    "t": 0.88,
    "s": 3.99,
    "d": -1.20,
    "total": 13.67
  }
