#%RAML 1.0 DataType
title: The definition of order types
version: v1

type: object
properties:
  oid:
    type: integer
    displayName: Order ID
  status:
    type: integer
    enum: [0, 1, 2, 3, 4]
  total: number
  profit: number
  date: datetime
  note?: string
  deliverFee?: number
  deliverDate?: date-only
  trackingNo?: string
  payment?: number
  lines:
    type: array
    items: !include orderline.raml
example: |
  {
    "oid": 1,
    "status": 2,
    "total": 23.67,
    "profit": 3.99,
    "date": "2016-03-01T14:30:03Z",
    "lines": [
      {
        "lid": 1,
        "pid": 1,
        "date": "2016-03-01T14:30:03Z",
        "total": 23.67,
        "profit": 3.99,
        "model": "SL33",
        "note": "A gift for brother",
        "q": 2,
        "purchase": {
          "p": 10.0, "t": 0.88, "s": 0.00, "d": -1.20, "total": 19.68
        },
        "sell": {
          "p": 10.0, "t": 0.88, "s": 3.99, "d": -1.20, "total": 23.67
        }
      }
    ]
  }
