#%RAML 1.0 DataType
displayName: Product Object
type: object
properties:
  pid:
    type: integer
    displayName: Product ID
  name: string
  cid:
    type: integer
    displayName: Category ID
  cname:
    type: string
    displayName: Category Name
  desc:
    type: string
    displayName: Production Description
    required: false
  price:
    type: number
    displayName: List price of product
  url?: string
example: |
  {
    "pid": 1,
    "name": "hot wheel",
    "cid": 1,
    "cname": "toy",
    "desc": "car model",
    "price": 3.99,
    "url": "http://a.b.c"
  }
